name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Backend Dependencies
      working-directory: ./pastificio-backend
      run: npm ci
    
    - name: Run Backend Tests
      working-directory: ./pastificio-backend
      run: npm run test:ci
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://localhost:27017/test
        JWT_SECRET: test-secret

  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Frontend Dependencies
      working-directory: ./pastificio-frontend-final
      run: npm ci --legacy-peer-deps
    
    - name: Run Frontend Tests
      working-directory: ./pastificio-frontend-final
      run: npm run test:ci
    
    - name: Build Frontend
      working-directory: ./pastificio-frontend-final
      run: npm run build

  build:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Confirmation
      run: |
        echo "✅ Backend tests passed"
        echo "✅ Frontend tests passed"
        echo "✅ Ready for deployment"
        echo "📦 Build successful!"
